services:
    - type: web
      name: kickrax-api
      runtime: node
      rootDir: backend
      buildCommand: npm install
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
      healthCheckPath: /api/health
      autoDeploy: true